[Next Gen]
type = drive

scope = drive

token = {"access_token":"ya29.a0AQvPyIPXClL-_B4_NU9fdMbRd4GM2M9e8cMgYlzBVAMl9Rp6ovosFTI-gbnIpSctJKkJQOe2R9bEmRJvONlosUlPtXwm6IM4alv-LPZ6ONPYMXt2xo_Lt8uroBlamBsPJAMUHG6q0qty_fJ2gtBiuhBwg_ij1cmpT8BdHezngjCORjBjBenfF-y9-5LhZkrucX8Zs9YaCgYKAUYSARISFQHGX2Mi-UM1nFm-DyoocqUt1LTKPA0206","token_type":"Bearer","refresh_token":"1//03Ea5I_mCTWwbCgYIARAAGAMSNwF-L9Irm_x8LRiFuABp2-5wN6WGbQ5-Vcz8ou8Avayvgs9CD5gb7bghn4-qOx6YpNUwxg6nSYs","expiry":"2026-05-21T00:26:10.3306438+05:00","expires_in":3599}

team_drive = 
